import { CheckCircle2, Copy, Download, FileUp, UploadCloud, UsersRound } from "lucide-react";
import { ChangeEvent, useMemo, useState } from "react";
import { assessmentRepository, type RosterRow } from "../domain/store";

function parseCsv(value: string): RosterRow[] {
  return value.trim().split(/\r?\n/).filter(Boolean).slice(value.includes("姓名") ? 1 : 0).map((line) => { const [name = "", department = "", position = ""] = line.split(","); return { name, department, position }; });
}

export default function PeoplePage() {
  const [campaigns] = useState(() => { assessmentRepository.seedDemoData(); return assessmentRepository.listCampaigns(); });
  const [campaignId, setCampaignId] = useState(campaigns[0]?.id ?? "");
  const [csv, setCsv] = useState("");
  const [message, setMessage] = useState("");
  const [errors, setErrors] = useState<{ row: number; message: string }[]>([]);
  const [copied, setCopied] = useState("");
  const participants = useMemo(() => assessmentRepository.listParticipants(campaignId), [campaignId, message]);
  const campaign = campaigns.find((item) => item.id === campaignId);
  const handleFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; file.text().then(setCsv); };
  const importRoster = () => { const report = assessmentRepository.importParticipants(campaignId, parseCsv(csv)); setMessage(`成功导入 ${report.imported.length} 人`); setErrors(report.errors); setCsv(""); };
  const copyLink = async (token: string) => { const link = `${window.location.origin}/assessment/${token}`; await navigator.clipboard?.writeText(link); setCopied(token); setTimeout(() => setCopied(""), 1600); };
  return <div className="admin-page"><div className="page-title-row"><div><span className="section-kicker">PEOPLE</span><h1>人员名单</h1><p>导入姓名、部门和岗位，生成可追踪的员工测评链接。</p></div><button className="button button-ghost" type="button" onClick={() => setCsv("姓名,部门,岗位\n李明,运营部,主管\n张倩,市场部,专员") }><Download size={17} /> 下载示例 CSV</button></div><section className="import-layout"><article className="admin-panel import-panel"><div className="panel-heading"><div><span className="section-kicker">IMPORT ROSTER</span><h2>导入名单</h2></div><FileUp size={20} className="heading-icon" /></div><label className="field-label" htmlFor="campaign-select">目标测评批次</label><select id="campaign-select" value={campaignId} onChange={(event) => setCampaignId(event.target.value)}>{campaigns.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><label className="field-label" htmlFor="csv-input">CSV 名单</label><textarea id="csv-input" aria-label="CSV 名单" value={csv} onChange={(event) => setCsv(event.target.value)} placeholder={"姓名,部门,岗位\n李明,运营部,主管"} rows={6} /><div className="import-hint"><UploadCloud size={15} /> 支持三列：姓名、部门、岗位；不会上传业务资料。</div><button className="button button-primary" type="button" onClick={importRoster} disabled={!csv.trim() || !campaignId}><UploadCloud size={17} /> 导入名单</button>{message && <p className="success-message" role="status"><CheckCircle2 size={15} /> {message}</p>}{errors.length > 0 && <div className="import-errors">{errors.map((error) => <span key={`${error.row}-${error.message}`}>第 {error.row} 行：{error.message}</span>)}</div>}</article><article className="admin-panel import-explain"><span className="section-kicker">LINK POLICY</span><h2>专属链接规则</h2><ul className="plain-list"><li><CheckCircle2 size={16} /> 每名员工在一个批次只能提交一次。</li><li><CheckCircle2 size={16} /> 提交后保留查看个人结果的权限。</li><li><CheckCircle2 size={16} /> 链接只显示姓名、部门和岗位，不要求上传材料。</li></ul></article></section><article className="admin-panel"><div className="panel-heading"><div><span className="section-kicker">{campaign?.name ?? "CURRENT CAMPAIGN"}</span><h2>已导入人员 <span className="heading-count">{participants.length}</span></h2></div><UsersRound size={20} className="heading-icon" /></div><div className="people-table-wrap"><table className="results-table people-table"><thead><tr><th>员工</th><th>部门</th><th>岗位</th><th>状态</th><th>专属链接</th></tr></thead><tbody>{participants.map((participant) => { const completed = Boolean(assessmentRepository.getResult(participant.id)); return <tr key={participant.id}><td><strong>{participant.name}</strong></td><td>{participant.department}</td><td>{participant.position}</td><td><span className={`completion-status ${completed ? "is-complete" : ""}`}>{completed ? "已完成" : "待开始"}</span></td><td><button className="copy-link-button" type="button" onClick={() => copyLink(participant.token)}><Copy size={14} /> {copied === participant.token ? "已复制" : "复制链接"}</button></td></tr>; })}</tbody></table></div></article></div>;
}
